- name: reset kubernetes cluster
  include: kubespray/reset.yml
  
- name: remove gpu components
  hosts: gpu-node
  tasks:
    - name: Remove the packages "nvidia docker2"
      apt:
        name: "{{ item }}"
        state: absent
        autoremove: yes
        purge: yes
      with_items: ['nvidia-container-runtime', 'nvidia-docker2', 'nvidia-container-runtime-hook']
    - name: remove /etc/docker/daemon.json
      file:
        path: /etc/docker/daemon.json
        state: absent
    - name: restart docker
      systemd:
        state: restarted
        daemon_reload: yes
        name: docker

- hosts: object-storage
  tasks:
    - name: disable minio service
      systemd:
        name: minio
        enabled: no
        state: stopped
        daemon_reload: yes

    - name: remove minio files
      file: 
        path: "{{ item }}" 
        state: absent 
      with_items: 
        - /etc/systemd/system/minio.service
        - /etc/default/minio
        - /bin/minio
        
- hosts: nfs-server
  tasks:
    - name: remove nfs server
      apt:
        name: nfs-kernel-server
        state: absent

    - name: remove minio, nfs conf files
      file: 
        path: "{{ item }}" 
        state: absent 
      with_items: 
        - /etc/exports