- name: install os packages
  hosts: all
  roles:
   - os

- name: scale kubernetes cluster
  include: kubespray/scale.yml

- name: enable gpu docker on server
  hosts: gpu-node
  roles:
   - gpu-server