- name: add http_proxy to /etc/environment 
  lineinfile:
    dest: /etc/environment
    regexp: "http_proxy.*$"
    line: "http_proxy={{ http_proxy }}"
    state: present
    backup: yes
    unsafe_writes: yes
  when:
    - http_proxy is defined
- name: add https_proxy to /etc/environment 
  lineinfile:
    dest: /etc/environment
    regexp: "https_proxy.*$"
    line: "https_proxy={{ https_proxy }}"
    state: present
    backup: yes
    unsafe_writes: yes
  when:
    - https_proxy is defined
- name: add no_proxy to /etc/environment
  lineinfile:
    dest: /etc/environment
    regexp: "no_proxy.*$"
    line: 'no_proxy={{ no_proxy_os }}'
    state: present
    backup: yes
    unsafe_writes: yes
  when:
    - http_proxy is defined or https_proxy is defined
- name: remove http_proxy to /etc/environment 
  lineinfile:
    dest: /etc/environment
    regexp: "http_proxy.*$"
    state: absent
    backup: yes
    unsafe_writes: yes
  when:
    - not http_proxy is defined
- name: remove https_proxy to /etc/environment 
  lineinfile:
    dest: /etc/environment
    regexp: "https_proxy.*$"
    state: absent
    backup: yes
    unsafe_writes: yes
  when:
    - not https_proxy is defined
- name: remove no_proxy to /etc/environment 
  lineinfile:
    dest: /etc/environment
    regexp: "no_proxy.*$"
    state: absent
    backup: yes
    unsafe_writes: yes
  when:
    - not http_proxy is defined and not https_proxy is defined