apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: @(Model.TenantName)
  name: @(Model.TenantName)
rules:
- apiGroups: [""]
  resources:
    - pods
    - pods/log
    - pods/status
    - services
    - configmaps
    - secrets
    - events
  verbs:
    - get
    - list
    - create
    - update
    - patch
    - watch
    - proxy
    - redirect
    - delete
    - deletecollection
- apiGroups: ["batch", "extensions"]
  resources:
    - jobs
  verbs:
    - get
    - list
    - create
    - update
    - patch
    - watch
    - delete
    - deletecollection