# KQIクラスタのデフォルト構成
nvidia_device_plugin_version: 1.0.0-beta
nvidia_driver: nvidia-384
install_nvidia_driver: false
nvidia_docker_packages:
    - nvidia-container-runtime=2.0.0+docker18.09.6-3
    - nvidia-docker2=2.0.3+docker18.09.6-3

ansible_python_interpreter: /usr/bin/python3

kubeadm_enabled: true

# 追加アプリのオフ
dashboard_enabled: false
efk_enabled: false
helm_enabled: false

# アラート回避
ignore_assert_errors: true
kubelet_fail_swap_on: false

# OSの予約リソース 
kubelet_custom_flags:
   - --system-reserved="cpu=100m,memory=100Mi,ephemeral-storage=1Gi"

docker_dns_servers_strict: false

# ネットワーク設定
kube_network_plugin: weave
kube_proxy_mode: iptables
weave_mode_seed: false
docker_options: >-
  {%- if docker_bip is defined %}
  --bip={{ docker_bip }} 
  {%- endif -%}
  {%- if docker_insecure_registries is defined %}
  {{ docker_insecure_registries | map('regex_replace', '^(.*)$', '--insecure-registry=\1' ) | list | join(' ') }}
  {%- endif %}
  --live-restore --graph={{ docker_daemon_graph }} {{ docker_log_opts }}

# /etc/environment用
# TODO: include_varsでkubesprayの変数を利用することを検討
no_proxy_os: >-
  {%- if http_proxy is defined or https_proxy is defined %}
  {%- for item in (groups['all']) |unique -%}
    {{item}},{{ hostvars[item]['access_ip'] | default(hostvars[item]['ip']) | default(hostvars[item]['ansible_default_ipv4']['address']) }},
  {%- endfor -%}
  {%- if additional_no_proxy is defined -%}
  {{ additional_no_proxy }},
  {%- endif -%}
  127.0.0.1,localhost,.local
  {%- endif %}