# 空の場合にエラーが出るのを回避する
dummy_data_test: ''

# insecure registryのテストを行う場合はコメントアウトをはずす
registry_server: "gitlab.local:1234" # docker loginで指定するサーバー
registry_user: "gitlab_user" # docker loginで使用するユーザー
registry_password: "gitlab_password" # docker loginで使用するユーザーのパスワード
test_image: "gitlab_test_project/image:tag" # docker pullで指定するイメージ