apiVersion: v1
kind: ConfigMap
metadata:
  name: "@(Model.Name)"
  namespace: "@(Model.NameSpace)"
data:
  prepare: 
  main: |
    # requirement: use tensorboard/tensorboard image   
    mkdir /tensorboard
    /usr/local/bin/tensorboard --logdir /kqi/output
  finish: |
    bash /kqi/scripts/common/prepare-kqi-conf
    sleep $EXPIRES_IN
    kqi training tensorboard-halt $TRAINING_ID