- name: install nfs server
  apt:
    name: nfs-kernel-server
    state: present
- name: Create mountable dir to /var/lib/kamonohashi/nfs
  file: 
    path: /var/lib/kamonohashi/nfs 
    state: directory 
- name: make /etc/exports
  copy:
    content: |
      /var/lib/kamonohashi/nfs *(rw,sync,no_subtree_check,no_root_squash)
    dest: /etc/exports
- name: restart nfs server
  systemd:
    state: restarted
    daemon_reload: yes
    name: nfs-kernel-server